### ISSUE TITLE
Project state fields

### ISSUE THREAD

**Issue by sirex** [python-dirbtuves/website#9]
Add project state fields:

- Implementation (repository) URL. Optional field.
- Project status (proposed, in progress, suspended, implemented). Default status should be "proposed".
- Project status description - a description where project status is described, for example if project was suspended, then an explanation why it was suspended could be added. This field should be optional.

Also after adding these fields, also project details page and project listing should be updated to display these new fields.

Project listing only should show status.

For status, consider using [Bootstrap labels](http://getbootstrap.com/components/#labels).

**Comment by iakovleva** [comment]
I have no idea why Travis failed as well as "make testall": relation "core_project" does not exist.
I made migrations. What else?

**Comment by sirex** [comment]
Can I see the code in pull request?

**Comment by iakovleva** [comment]
Done

**Comment by niekas** [comment]
@vomaxHELLnO gets same error. This error occurs when ```core.Project``` model is used in anyway in a migration. We couldn't find the accurate reason, but it seems like migration history is corrupt. Removing all ```core``` migration history and creating new initial ```core``` migration solved the issue.

**Comment by niekas** [comment]
Sorry, removal of history didn't solve the problem. ```make testall``` still fails.

**Comment by niekas** [comment]
The problem is caused, because Django does not handle Project model transferring from ```website``` to ```core``` module. I have changed migration history so that ```Project``` model is in ```core``` module from the beginning. Probably this approach is not best, but I wasn't able to find other way. I've created pull request for my migration fix: https://github.com/python-dirbtuves/website/pull/50

**Comment by sirex** [comment]
Sorry, that was my error, fixed it in c4c33f9426a7a14429268c6babf3548d6b8ac844.

**Comment by niekas** [comment]
Implemented and merged: https://github.com/python-dirbtuves/website/pull/48
